name: Rust Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        platform:
          - target: aarch64-unknown-linux-musl
            command: both

          - target: i686-unknown-linux-musl
            command: both

          - target: x86_64-unknown-linux-musl
            command: both
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.platform.target }}
          path: ./target/${{ matrix.platform.target }}/release/cli ./cli
          retention-days: 1
  docker_image:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifactrs
        uses: actions/download-artifact@v4
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          tag: latest
          platform: linux/amd64,linux/arm64
          imageName: ilteoood/nmt
          publish: true
          dockerUser: ilteoood
          dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
