name: Rust Build and Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses:  actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Test
        run: cargo test
  build:
    needs: test
    strategy:
      matrix:
        platform:
          - target: aarch64-unknown-linux-musl
          - target: i686-unknown-linux-musl
          - target: x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y musl-tools musl-dev

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.platform.target }}
          path: ./target/${{ matrix.platform.target }}/release/cli ./cli
          retention-days: 1
  docker_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifactrs
        uses: actions/download-artifact@v4
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          tag: latest
          platform: linux/amd64,linux/arm64
          imageName: ilteoood/nmt
          publish: true
          dockerUser: ilteoood
          dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
